name: Imjoon Ha
description: Blogging about Developing Software
meta_description: "Blogging about Developing Software"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'conquernos.github.io'
google_analytics: 'UA-137476599-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://conquernos.github.io'
author:         'Your Name'
